
[build]
  base = "fe"
  command = "pnpm install --ignore-workspace --prod=false --no-frozen-lockfile && pnpm build"
  publish = "dist"

[context.production.environment]
  VITE_API_URL = "https://video-downloader-produk.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
